apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: healsync
data:
  FLASK_ENV:         "production"
  PRIMARY_DB_HOST:   "mysql-primary"
  PRIMARY_DB_PORT:   "3306"
  PRIMARY_DB_NAME:   "healsync"
  PRIMARY_DB_USER:   "root"
  SECONDARY_DB_HOST: "mysql-secondary"
  SECONDARY_DB_PORT: "3306"
  SECONDARY_DB_NAME: "healsync"
  SECONDARY_DB_USER: "root"
  ACTIVE_DB:         "primary"
  CLUSTER_ROLE:      "primary"
  CLUSTER_REGION:    "us-east-1"
  RECOVERY_THRESHOLD: "3"
  FAILOVER_MONITOR_ENABLED: "true"
  EVENT_LOG_LIMIT: "500"
  WAIT_FOR_REPLICATION: "true"
  REPLICATION_STRICT_ACK: "true"
  REPLICATION_WAIT_TIMEOUT_SECONDS: "5"
  REPLICATION_POLL_INTERVAL_SECONDS: "0.2"
